name: CI/CD Pipeline with Vault

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v2.4.0
        with: 
          url: 
