# .github/workflows/deploy.yml
name: Access MongoDB Credentials from Vault

on:
  push:
    branches:
      - master # This must match your repository's branch name

permissions:
  id-token: write # Required to get the OIDC token
  contents: read  # Required to checkout the code

env:
  VAULT_ADDR: "https://vault-hoodk-public-vault-fcef8209.ef380317.z1.hashicorp.cloud:8200"
  VAULT_NAMESPACE: "admin"

jobs:
  get-creds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Vault Secrets
        id: auth
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ env.VAULT_ADDR }}
          namespace: ${{ env.VAULT_NAMESPACE }}
          method: jwt
          role: github-hoodk-role # The Vault role we created
          secrets: |
                    database/creds/hoodk-role username | MONGO_USER
                    database/creds/hoodk-role password | MONGO_PASSWORD

      - name: Use the MongoDB Credentials
        run: |
          echo "--- Dynamic Credentials Retrieved ---"
          echo "Username: ${{ steps.auth.outputs.MONGO_USER }}"
          echo "Password: ${{ steps.auth.outputs.MONGO_PASSWORD }}"

          # NOTE: These credentials are now available as environment variables for use in
          # subsequent steps, such as connecting to your database.
          # For example, to connect your application:
          # your_app_command --user=$MONGO_USER --password=$MONGO_PASSWORD

      - name: Vault Debugging
        if: ${{ failure() }}
        run: |
          echo "--- Troubleshooting Failed Step ---"
          echo "Vault Address: ${{ env.VAULT_ADDR }}"
          echo "Vault Namespace: ${{ env.VAULT_NAMESPACE }}"
          echo "Role: github-hoodk-role"
          echo "Secrets Path: database/creds/hoodk-role"
          echo "Review the logs above for any errors from Vault. Check the following:"
          echo "1. Vault server is unsealed and running."
          echo "2. The 'github-hoodk-role' has the correct bound claims (repository, branch)."
          echo "3. The Vault token used by GitHub Actions has the correct policy permissions to read the secrets."